# Matugen template for Sway
# Generated file: ~/.config/sway/colors.conf

#       focused                 unfocused               focused_inactive        urgent
client.focused         #ffb689 #ffb689 #512300 #ffb689 #ffb689
client.unfocused       #19120d #19120d #f0dfd7 #9f8d83 #9f8d83
client.focused_inactive #261e19 #261e19 #f0dfd7 #9f8d83 #9f8d83
client.urgent          #ffb4ab #ffb4ab #690005 #ffb4ab #ffb4ab
