include=~/.config/fuzzel/colors.ini

# Global Settings
dpi-aware=no
width=40
lines=15
minimal-lines=1
icons-enabled=false

# UI
hide-prompt=no
font=JetbrainsMono Nerd Font:size=12:antialias=true:hinting=true
prompt="> "
terminal=foot
layer=overlay
line-height=32

[border]
width=2
radius=0

[key-bindings]
next=none
prev=none
next-with-wrap=Down Control+n
prev-with-wrap=Up Control+p
