/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright 2020-2021 The River Developers
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface river_layout_v3_interface;
extern const struct wl_interface wl_output_interface;

static const struct wl_interface *river_layout_v3_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&river_layout_v3_interface,
	&wl_output_interface,
	NULL,
};

static const struct wl_message river_layout_manager_v3_requests[] = {
	{ "destroy", "", river_layout_v3_types + 0 },
	{ "get_layout", "nos", river_layout_v3_types + 5 },
};

WL_PRIVATE const struct wl_interface river_layout_manager_v3_interface = {
	"river_layout_manager_v3", 2,
	2, river_layout_manager_v3_requests,
	0, NULL,
};

static const struct wl_message river_layout_v3_requests[] = {
	{ "destroy", "", river_layout_v3_types + 0 },
	{ "push_view_dimensions", "iiuuu", river_layout_v3_types + 0 },
	{ "commit", "su", river_layout_v3_types + 0 },
};

static const struct wl_message river_layout_v3_events[] = {
	{ "namespace_in_use", "", river_layout_v3_types + 0 },
	{ "layout_demand", "uuuuu", river_layout_v3_types + 0 },
	{ "user_command", "s", river_layout_v3_types + 0 },
	{ "user_command_tags", "2u", river_layout_v3_types + 0 },
};

WL_PRIVATE const struct wl_interface river_layout_v3_interface = {
	"river_layout_v3", 2,
	3, river_layout_v3_requests,
	4, river_layout_v3_events,
};

