[icons]
icons = "material-nf"
[icons.overrides]
bat = [
 "󰁺",
 "󰁻",
 "󰁼",
 "󰁽",
 "󰁾",
 "󰁿",
 "󰂀",
 "󰂁",
 "󰂂",
 "󰁹"
]
bat_not_available = "!"
bat_charging = [
 "󰢜",
 "󰂆",
 "󰂇",
 "󰂈",
 "󰢝",
 "󰂉",
 "󰢞",
 "󰂊",
 "󰂋",
 "󰂅"
]
bluetooth =" 󰂯 "
headphones = " 󰋋 "
microphone = " 󰍬 "
microphone_muted = ""
mouse = " 󰍽 "
time = ""
volume = [
 "󰕿",
 "󰖀",
 "󰕾",
]
volume_muted =  "󰖁"
backlight = [
    "󰃠",
    "󰃟",
    "󰃝",
    "󰃞",

]

[theme]
theme = "plain"
[theme.overrides]
good_fg = "#ffffff"
info_fg = "#ffffff"
idle_fg = "#ffffff"
separator = " "


[[block]]
block = "custom"
command = "echo $(/home/daniel/scripts/checkup.sh)"
interval = 86400
[[block.click]]
button = "left"
cmd = "/home/daniel/scripts/prompt.sh"

[[block]]
block = "hueshift"
hue_shifter = "wlsunset"
format = " 󰽥 "
step = 100
click_temp = 4500

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = false
headphones_indicator = true
[block.theme_overrides]
warning_fg="#676767"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 4"
[block.format]
full = "$icon"
short = "$icon"



[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
show_volume_when_muted = false
headphones_indicator = true
max_vol = 150
format = " $icon "
[block.theme_overrides]
warning_fg="#ffffff"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 3"


[[block]]
block = "bluetooth"
mac = ""
disconnected_format = ""

[[block]]
block = "backlight"
step_width = 5
minimum = 15
maximum = 100
invert_icons = true
format = " $icon "

[[block]]
block = "net"
device = "wlan0"
inactive_format = " 󰤮 "
missing_format = " 󰤮 "
interval = 5
[block.format]
short = " $icon "
full = " $icon "
[[block.click]]
button = "left"
cmd = "networkmanager_dmenu"

[[block]]
block = "battery"
device = "BAT1"
driver = "upower"
[block.format]
full = " $percentage $icon"
short = " $percentage $icon"
[block.full_format]
full = " $percentage $icon"
short = "$percentage $icon"
[[block.click]]
button = "left"
cmd = "tlpui"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%R %d/%m') "
interval = 60

