font = "JetBrainsMono Nerd Font 10"
height = 24
command = "i3status-rs"

background = "#000000"
color = "#ffffff"
separator = "#ffffff"
tag_fg = "#93a1a1"
tag_bg = "#000000"
tag_focused_fg = "#ffffff"
tag_focused_bg = "#000000"
tag_urgent_fg = "#ff0000"
tag_urgent_bg = "#000000"
tag_inactive_fg = "#ffffff"
tag_inactive_bg = "#282828ff"

tags_padding = 12.0


position = "top"                 # either "top" or "bottom"
hide_inactive_tags = true
invert_touchpad_scrolling = true
show_layout_name = false
blend = false                    # whether tags/blocks colors should blend with bar's background
show_mode = false
