/* Generated by wayland-scanner 1.23.0 */

/*
 * Copyright 2020 The River Developers
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface zriver_output_status_v1_interface;
extern const struct wl_interface zriver_seat_status_v1_interface;

static const struct wl_interface *river_status_unstable_v1_types[] = {
	NULL,
	&zriver_output_status_v1_interface,
	&wl_output_interface,
	&zriver_seat_status_v1_interface,
	&wl_seat_interface,
	&wl_output_interface,
	&wl_output_interface,
};

static const struct wl_message zriver_status_manager_v1_requests[] = {
	{ "destroy", "", river_status_unstable_v1_types + 0 },
	{ "get_river_output_status", "no", river_status_unstable_v1_types + 1 },
	{ "get_river_seat_status", "no", river_status_unstable_v1_types + 3 },
};

WL_PRIVATE const struct wl_interface zriver_status_manager_v1_interface = {
	"zriver_status_manager_v1", 4,
	3, zriver_status_manager_v1_requests,
	0, NULL,
};

static const struct wl_message zriver_output_status_v1_requests[] = {
	{ "destroy", "", river_status_unstable_v1_types + 0 },
};

static const struct wl_message zriver_output_status_v1_events[] = {
	{ "focused_tags", "u", river_status_unstable_v1_types + 0 },
	{ "view_tags", "a", river_status_unstable_v1_types + 0 },
	{ "urgent_tags", "2u", river_status_unstable_v1_types + 0 },
	{ "layout_name", "4s", river_status_unstable_v1_types + 0 },
	{ "layout_name_clear", "4", river_status_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zriver_output_status_v1_interface = {
	"zriver_output_status_v1", 4,
	1, zriver_output_status_v1_requests,
	5, zriver_output_status_v1_events,
};

static const struct wl_message zriver_seat_status_v1_requests[] = {
	{ "destroy", "", river_status_unstable_v1_types + 0 },
};

static const struct wl_message zriver_seat_status_v1_events[] = {
	{ "focused_output", "o", river_status_unstable_v1_types + 5 },
	{ "unfocused_output", "o", river_status_unstable_v1_types + 6 },
	{ "focused_view", "s", river_status_unstable_v1_types + 0 },
	{ "mode", "3s", river_status_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zriver_seat_status_v1_interface = {
	"zriver_seat_status_v1", 3,
	1, zriver_seat_status_v1_requests,
	4, zriver_seat_status_v1_events,
};

