#!/bin/sh

##############################################
# Key bindings
##############################################

mod=Mod4

# Application Launchers
riverctl map normal $mod Return spawn 'foot'
riverctl map normal $mod+Shift s spawn '~/scripts/screenshot_river.sh'
riverctl map normal $mod b spawn 'firefox'
riverctl map normal $mod h spawn 'foot -e btop'
riverctl map normal $mod y spawn 'foot -e yazi'
riverctl map normal $mod v spawn 'foot -e nvim'
riverctl map normal $mod p spawn 'pavucontrol'
riverctl map normal $mod n spawn 'networkmanager_dmenu'
riverctl map normal $mod t spawn 'thunar'
riverctl map normal $mod c spawn 'code'
riverctl map normal Alt Tab spawn 'rofi -show window'

#toggle layout
riverctl map normal $mod Tab send-layout-cmd wideriver "--layout-toggle"
# mod+mouse bindings
riverctl map-pointer normal $mod BTN_LEFT move-view

# Volume and Brightness Controls
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+ && ~/scripts/volume.sh"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && ~/scripts/volume.sh"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && ~/scripts/muteaudio.sh"
riverctl map normal None XF86AudioMicMute spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && ~/scripts/mic.sh"
riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl set +5% && ~/scripts/brightness.sh"
riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 5%- && ~/scripts/brightness.sh"

# Clipboard History
riverctl map normal $mod+Shift v spawn '/home/daniel/scripts/cliphist-rofi'

# Kill focused window
riverctl map normal $mod q close

# Start application launcher
riverctl map normal $mod d spawn 'j4-dmenu-desktop --no-generic --skip-i3-exec-check -f --dmenu bemenu -t foot'

# Restart River
riverctl map normal $mod+Shift C spawn "${XDG_CONFIG_HOME}/river/init >/dev/null && notify-send 'River' 'Refreshed'"

# Exit River
riverctl map normal $mod+Shift e spawn '/home/daniel/scripts/dmenu_logout_river.sh'

# Open update prompt
riverctl map normal $mod+Shift u spawn '/home/daniel/scripts/prompt.sh'

# Layout stuff
riverctl map normal $mod Left focus-view left
riverctl map normal $mod Down focus-view next
riverctl map normal $mod Up focus-view previous
riverctl map normal $mod Right focus-view right

riverctl map normal $mod+Shift Left swap left
riverctl map normal $mod+Shift Down swap down
riverctl map normal $mod+Shift Up swap up
riverctl map normal $mod+Shift Right swap right

riverctl map normal $mod+Control Left send-layout-cmd wideriver "--ratio -0.05"
riverctl map normal $mod+Control Right send-layout-cmd wideriver "--ratio +0.05"
riverctl map normal $mod+Control Down send-layout-cmd wideriver "--count -1"
riverctl map normal $mod+Control Up send-layout-cmd wideriver "--count +1"

# Change output
riverctl map normal $mod o spawn "riverctl focus-output next"
# Send to next output
riverctl map normal $mod+Shift o spawn "riverctl send-to-output next"

# Workspaces
for i in $(seq 1 9); do
  riverctl map normal $mod $i set-focused-tags $((1 << ($i - 1)))
  riverctl map normal $mod+Shift $i set-view-tags $((1 << ($i - 1)))
  riverctl map normal $mod+Control $i toggle-focused-tags $((1 << ($i - 1)))
done

all_tags_mask=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags_mask

# Fullscreen mode
riverctl map normal $mod f toggle-fullscreen
riverctl map normal $mod+Shift space toggle-float
riverctl map normal $mod space focus-float

# Scratchpad
scratch_tag=$((1 << 20))
riverctl map normal $mod minus toggle-focused-tags ${scratch_tag} # toggle the scratchpad
riverctl map normal $mod+Shift minus set-view-tags ${scratch_tag} # send windows to the scratchpad
all_but_scratch_tag=$((((1 << 32) - 1) ^ $scratch_tag))
riverctl spawn-tagmask ${all_but_scratch_tag}

##############################################
# Input configuration
##############################################

# Keyboard configuration
riverctl keyboard-layout "es"

# Touchpad configuration
for pad in $(riverctl list-inputs | grep -i touchpad); do
  riverctl input $pad events enabled
  riverctl input $pad tap enabled
  riverctl input $pad disable-while-typing enabled
  riverctl input $pad natural-scroll enabled
  riverctl input $pad drag-lock enabled
done

##############################################
# Behavoiur & Autostart
##############################################

riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor normal

riverctl rule-add ssd
riverctl rule-add -title "Open File" float
riverctl rule-add -title "Open Folder" float

# Setup dbus
riverctl spawn "dbus-update-activation-environment --systemd SEATD_SOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment SEATD_SOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

# Set layout manager
riverctl default-layout wideriver

# Autostart applications
executes="swaybg swayidle /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 i3bar-river wl-paste wideriver dunst"
for execute in $executes; do
  pidof -q "$execute" && continue
  case $execute in
  "swaybg") "$execute" -i ~/Pictures/montain.webp -m fill & ;;
  "swayidle") "$execute" -w before-sleep 'pidof -q hyprlock || hyprlock -q' & ;;
  "wl-paste") "$execute" --watch cliphist store & ;;
  "wideriver") "$execute" --layout left \
    --layout-alt monocle \
    --stack even \
    --count-master 1 \
    --ratio-master 0.55 \
    --smart-gaps \
    --inner-gaps 4 \
    --outer-gaps 4 \
    --border-width 2 \
    --border-width-monocle 2 \
    --border-width-smart-gaps 0 \
    --border-color-focused "0x93a1a1" \
    --border-color-focused-monocle "0x93a1a1" \
    --border-color-unfocused "0x333333" & ;;
  *) "$execute" & ;;
  esac

done >/dev/null 2>&1
