# Main background and foreground
theme[main_bg] = "#0f1512"
theme[main_fg] = "#dee4de"

# Title and headings
theme[title] = "#dee4de"
theme[hi_fg] = "#8cd5b4"

# Selected/Active items
theme[selected_bg] = "#8cd5b4"
theme[selected_fg] = "#003826"

# Inactive items
theme[inactive_fg] = "#bfc9c2"

# Graph/Chart colors
theme[graph_text] = "#dee4de"
theme[meter_bg] = "#404944"
theme[proc_misc] = "#a6ccdf"
theme[proc_start] = "#8cd5b4"
theme[proc_mid] = "#005139"
theme[proc_end] = "#b3ccbe"

# Cpu/Mem/Disk graphs
theme[cpu_start] = "#8cd5b4"
theme[cpu_mid] = "#005139"
theme[cpu_end] = "#a6ccdf"

theme[mem_start] = "#8cd5b4"
theme[mem_mid] = "#005139"
theme[mem_end] = "#a6ccdf"

theme[net_start] = "#8cd5b4"
theme[net_mid] = "#005139"
theme[net_end] = "#a6ccdf"
