#!/bin/sh

DEVICE="platform::kbd_backlight"

if [ "$1" = "up" ]; then
  brightnessctl --device="$DEVICE" set +1 >/dev/null 2>&1
elif [ "$1" = "down" ]; then
  brightnessctl --device="$DEVICE" set 1- >/dev/null 2>&1
else
  exit 1
fi
