# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x{{colors.surface.default.hex_stripped}}ff
bordercolor = 0x{{colors.outline.default.hex_stripped}}ff
dropcolor = 0x{{colors.primary.default.hex_stripped}}80
splitcolor = 0x{{colors.tertiary.default.hex_stripped}}ff
focuscolor = 0x{{colors.primary.default.hex_stripped}}ff
maximizescreencolor = 0x{{colors.secondary.default.hex_stripped}}ff
urgentcolor = 0x{{colors.error.default.hex_stripped}}ff
scratchpadcolor = 0x{{colors.tertiary.default.hex_stripped}}ff
globalcolor = 0x{{colors.primary_container.default.hex_stripped}}ff
overlaycolor = 0x{{colors.secondary_container.default.hex_stripped}}ff
jump_label_decorate_fg_color = 0x{{colors.on_surface.default.hex_stripped}}ff
jump_label_decorate_bg_color = 0x{{colors.surface_container_high.default.hex_stripped}}ff
jump_label_decorate_focus_fg_color = 0x{{colors.on_primary.default.hex_stripped}}ff
jump_label_decorate_focus_bg_color = 0x{{colors.primary.default.hex_stripped}}ff
jump_label_decorate_border_color = 0x{{colors.outline.default.hex_stripped}}ff
group_bar_decorate_fg_color = 0x{{colors.on_surface.default.hex_stripped}}ff
group_bar_decorate_bg_color = 0x{{colors.surface_container_high.default.hex_stripped}}ff
group_bar_decorate_focus_fg_color = 0x{{colors.on_primary.default.hex_stripped}}ff
group_bar_decorate_focus_bg_color = 0x{{colors.primary.default.hex_stripped}}ff
group_bar_decorate_border_color = 0x{{colors.outline.default.hex_stripped}}ff
