# ~/.config/matugen/templates/swaylock.conf

image=~/Pictures/wallpaper.jpg
show-failed-attempts
ignore-empty-password
indicator-idle-visible
font=JetBrains Mono Nerd Font
line-uses-inside

# Outside (background)
color={{colors.surface.default.hex}}ff

# Text
text-color={{colors.on_surface.default.hex}}ff
text-clear-color={{colors.on_secondary_container.default.hex}}ff
text-ver-color={{colors.on_primary_container.default.hex}}ff
text-wrong-color={{colors.on_error_container.default.hex}}ff
text-caps-lock-color={{colors.on_tertiary_container.default.hex}}ff

# Ring
ring-color={{colors.primary.default.hex}}ff
ring-clear-color={{colors.secondary.default.hex}}ff
ring-ver-color={{colors.primary.default.hex}}ff
ring-wrong-color={{colors.error.default.hex}}ff
ring-caps-lock-color={{colors.tertiary.default.hex}}ff

# Inside
inside-color={{colors.surface_container.default.hex}}cc
inside-clear-color={{colors.secondary_container.default.hex}}cc
inside-ver-color={{colors.primary_container.default.hex}}cc
inside-wrong-color={{colors.error_container.default.hex}}cc
inside-caps-lock-color={{colors.tertiary_container.default.hex}}cc

# Separator
separator-color={{colors.outline_variant.default.hex}}00

# Highlights
key-hl-color={{colors.primary_container.default.hex}}ff
caps-lock-key-hl-color={{colors.tertiary.default.hex}}ff
bs-hl-color={{colors.error.default.hex}}ff
caps-lock-bs-hl-color={{colors.error.default.hex}}ff

# Layout
layout-bg-color={{colors.surface_container.default.hex}}aa
layout-border-color={{colors.outline.default.hex}}ff
layout-text-color={{colors.on_surface.default.hex}}ff
